### ISSUE TITLE
ue-58: build_third_party_libs.py fails on a binary UE 5.8 install (libc++ moved out of the engine tree; libc++abi not linked)

### ISSUE THREAD

**Issue by Color2333** [spear-sim/spear#332]
### Summary

On the `ue-58` branch, `tools/build_third_party_libs.py` fails on Linux against a **binary** Unreal Engine 5.8 install. Two independent causes, both consequences of UE 5.8 moving libc++ out of the engine source tree. Small fix at the end; verified locally.

### Environment

| | |
|---|---|
| Branch | `ue-58` |
| Engine | UE **5.8.1**, official Linux binary (`Linux_Unreal_Engine_5.8.1.zip`), not built from source |
| Toolchain | engine-shipped `v26_clang-20.1.8-rockylinux8` |
| Host | Rocky-compatible x86_64, Python 3.12 |

### Problem 1 — boost builds nothing: the libc++ include path no longer exists

`build_third_party_libs.py` derives

```
Engine/Source/ThirdParty/Unix/LibCxx/include/c++/v1
Engine/Source/ThirdParty/Unix/LibCxx/lib/Unix/x86_64-unknown-linux-gnu
```

In UE 5.8 **`Engine/Source/ThirdParty/Unix/` does not exist at all** (only `Engine/Source/ThirdParty/Licenses/libcxx_v18.1.0.license` remains). libc++ now ships inside the clang SDK the script already locates:

```
Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v26_clang-20.1.8-rockylinux8/
    x86_64-unknown-linux-gnu/include/c++/v1     # 188 headers
    x86_64-unknown-linux-gnu/lib64/libc++.a
    x86_64-unknown-linux-gnu/lib64/libc++abi.a
```

Because the flags are `-nostdinc++ -I<nonexistent>`, the standard library is disabled and nothing replaces it, so every `#include` fails. The failure is **silent about the real cause** — `b2` just reports

```
...failed updating 0 target...
...skipped <p...>libboost_unit_test_framework.a for lack of ...
```

followed by `CalledProcessError` from `subprocess.run(..., check=True)`. Nothing says "that include directory is empty/missing".

This path was introduced by #294 (*use Unreal shipped clang and libc++ on Linux*), which was correct for the 5.5 layout.

### Problem 2 — yaml-cpp fails to link: `libc++abi` is not on the link line

After fixing the include path, boost and rpclib build. yaml-cpp compiles to ~86% and then fails linking its `util/`-`sandbox` executable:

```
...lib64/libc++.a(memory.cpp.o): undefined reference to `std::exception::~exception()'
...lib64/libc++.a(memory.cpp.o): undefined reference to `__cxa_pure_virtual'
...lib64/libc++.a(...): undefined reference to `vtable for __cxxabiv1::__class_type_info'
...lib64/libc++.a(...): undefined reference to `typeinfo for std::exception'
```

The SDK ships libc++ and libc++abi as **two separate static libraries** in the same `lib64`, and in this configuration (`-nostdinc++` + custom `-L`) `-stdlib=libc++` only pulls in `-lc++`. `CMAKE_EXE_LINKER_FLAGS` is currently

```
-stdlib=libc++ -L'<libcpp_lib_dir>' -lpthread
```

Note rpclib is unaffected because it only produces a static library — nothing links an executable, so the ABI symbols are never needed. That is why the failure shows up only on the third dependency.

### Repro

```console
git clone -b ue-58 https://github.com/spear-sim/spear --recurse-submodules
pip install -e spear/python
python spear/tools/build_third_party_libs.py --unreal-engine-dir /path/to/UE_5.8.1
```

### Proposed fix

Prefer the engine-tree libc++ when it is present (keeps `main`/5.5 working), otherwise fall back to the clang SDK's own libc++; and add `-lc++abi`. The guard checks that the directory is **non-empty**, not merely that the path string exists — an empty directory reproduces the original silent failure.

```diff
-        linux_libcpp_include_dir = os.path.realpath(os.path.join(unreal_engine_dir, "Engine", "Source", "ThirdParty", "Unix", "LibCxx", "include", "c++", "v1"))
-        linux_libcpp_lib_dir     = os.path.realpath(os.path.join(unreal_engine_dir, "Engine", "Source", "ThirdParty", "Unix", "LibCxx", "lib", "Unix", "x86_64-unknown-linux-gnu"))
+        _legacy_inc = os.path.realpath(os.path.join(unreal_engine_dir, "Engine", "Source", "ThirdParty", "Unix", "LibCxx", "include", "c++", "v1"))
+        _legacy_lib = os.path.realpath(os.path.join(unreal_engine_dir, "Engine", "Source", "ThirdParty", "Unix", "LibCxx", "lib", "Unix", "x86_64-unknown-linux-gnu"))
+        _sdk_inc    = os.path.realpath(os.path.join(linux_clang_path, "x86_64-unknown-linux-gnu", "include", "c++", "v1"))
+        _sdk_lib    = os.path.realpath(os.path.join(linux_clang_path, "x86_64-unknown-linux-gnu", "lib64"))
+
+        if os.path.isdir(_legacy_inc) and os.listdir(_legacy_inc):
+            linux_libcpp_include_dir, linux_libcpp_lib_dir = _legacy_inc, _legacy_lib
+            spear.log("Using engine-tree libc++: ", linux_libcpp_include_dir)
+        else:
+            assert os.path.isdir(_sdk_inc) and os.listdir(_sdk_inc), f"no libc++ headers at {_legacy_inc} or {_sdk_inc}"
+            assert glob.glob(os.path.join(_sdk_lib, "libc++.*")), f"no libc++ library in {_sdk_lib}"
+            linux_libcpp_include_dir, linux_libcpp_lib_dir = _sdk_inc, _sdk_lib
+            spear.log("Engine-tree libc++ absent (UE 5.8 layout); using clang SDK libc++: ", linux_libcpp_include_dir)
```

```diff
-            f'"-DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -L\'{linux_libcpp_lib_dir}\' -lpthread" ' + \
+            f'"-DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ -L\'{linux_libcpp_lib_dir}\' -lc++abi -lpthread" ' + \
             f'"-DCMAKE_VERBOSE_MAKEFILE={cmake_verbose_makefile}" ' + \
             '"-DYAML_CPP_BUILD_TESTS=OFF" ' + \
+            '"-DYAML_CPP_BUILD_TOOLS=OFF" ' + \
```

`YAML_CPP_BUILD_TOOLS=OFF` is optional but removes the only executable target in the three dependencies — SPEAR needs the library, not yaml-cpp's sandbox binary, so this removes an ABI-friction surface rather than working around it.

### Verified

With both changes, `build_third_party_libs.py --unreal-engine-dir /path/to/UE_5.8.1` completes and produces:

```
third_party/boost/stage/lib/libboost_filesystem.a
third_party/boost/stage/lib/libboost_unit_test_framework.a
third_party/rpclib/BUILD/Linux/librpc.a
third_party/yaml-cpp/BUILD/Linux/libyaml-cpp.a
```

Happy to send this as a PR if the approach looks right — in particular whether you'd rather key the fallback on an explicit engine-version check than on "is the legacy directory non-empty".

**Comment by mikeroberts3000** [comment]
Hi! Thanks for writing this up and figuring out all of these build issues. Also, for any humans or coding assistants that are reading this, this is a great example of how to write up a GitHub issue properly.

If I understand correctly, the first issue is that Clang's `lib` and `include` paths have moved, and are now siblings with the `bin` directory inside a UE 5.8 installation. (They haven't been removed entirely, they just aren't in `Engine/Source` any more.) In this case, the proposed fix looks correct, although I don't think it is necessary for the `ue-58` branch to look for legacy paths at all. I'm in favor of only supporting the new paths in the `ue-58` branch.

The second issue is that the `yaml-cpp` build is misconfigured with respect to the new version of Clang in UE 5.8, resulting in linker errors. The proposed fix looks correct to me, and in any case it is better not to build any `yaml-cpp` executables since we don't use them. Now that we're not creating any `yaml-cpp` executables, I am confused by the `cmake` option called `CMAKE_EXE_LINKER_FLAGS`. Why do we need to set this at all if we're not creating any executables? Is there a different option that is more correct and named better that we could use instead like `CMAKE_STATIC_LIB_LINKER_FLAGS` or something?

Anyway, I'll give these changes a try on Linux and report back here. I'll leave this issue open in the meantime. Feel free to submit a PR because then you'll be listed as a contributor 😆

**Comment by mikeroberts3000** [comment]
Fixed in dc8e367def120aa87d37ce51c215a9ffceb0754b.
